"""Document intelligence package.

All implementations live in ``app.document_intelligence``.  The sub-modules
under this package re-export those symbols so callers can import from either
``app.document_intelligence`` or ``app.intelligence``.
"""
from __future__ import annotations

from app.intelligence.classification import (
    _llm_classify_columns,
    _safe_semantic_type,
    _wrap_exact_match,
    classify_columns_semantic,
)
from app.intelligence.models import (
    ColumnClassification,
    ColumnSchema,
    DocumentSchema,
    MatchEntry,
    QueryPlan,
    QueryResult,
    SemanticType,
    SheetSchema,
)
from app.intelligence.prompts import (
    _DEFAULT_PRICING,
    _MAX_COLUMN_NAME_CHARS,
    _MAX_INTENT_CHARS,
    _MAX_SAMPLE_VALUE_CHARS,
    _MODEL_PRICING,
    _SYSTEM_PROMPT_DATA_CONTEXT,
)
from app.intelligence.query import (
    _DOC_COST_PREFIX,
    _DOC_COST_TTL_SECONDS,
    _MD_TABLE_ROW_RE,
    _PROSE_CHUNK_SIZE,
    _PROSE_SEMAPHORE_LIMIT,
    _QUERY_CACHE_PREFIX,
    _QUERY_CACHE_TTL_SECONDS,
    _QUERY_KEYS_PREFIX,
    _TABULAR_CHUNK_MAX_CHARS,
    _TABULAR_ROWS_PER_CHUNK,
    _TABULAR_SEMAPHORE_LIMIT,
    _accumulate_usage,
    _build_query_plan,
    _check_budget,
    _chunk_tabular_text,
    _estimate_cost,
    _extract_from_chunk,
    _extract_prose,
    _extract_tabular,
    _extract_tabular_chunk,
    _extract_tabular_llm,
    _filter_columns,
    _get_query_cache_key,
    _load_query_cache,
    _load_schema,
    _log_query_cost,
    _merge_chunk_results,
    _parse_markdown_table,
    _query_document_impl,
    _store_query_cache,
    invalidate_query_cache,
    query_document,
)
from app.intelligence.schema import (
    _LOCK_POLL_INTERVAL_SECONDS,
    _LOCK_POLL_TIMEOUT_SECONDS,
    _LOCK_TTL_SECONDS,
    _SCHEMA_CACHE_PREFIX,
    _SCHEMA_LOCK_PREFIX,
    _compute_schema,
    _enrich_sheets_with_llm,
    _extract_markdown_table_as_csv,
    _extract_sheets_from_doc,
    _generate_schema_summary,
    _parse_csv_schema,
    _parse_docx_schema,
    _parse_excel_schema,
    _parse_image_schema,
    _parse_pdf_schema,
    _parse_prose_schema,
    _poll_for_schema,
    analyze_schema,
)

__all__ = [
    # models
    "SemanticType",
    "ColumnClassification",
    "ColumnSchema",
    "SheetSchema",
    "DocumentSchema",
    "QueryPlan",
    "MatchEntry",
    "QueryResult",
    # prompts
    "_MAX_COLUMN_NAME_CHARS",
    "_MAX_SAMPLE_VALUE_CHARS",
    "_MAX_INTENT_CHARS",
    "_SYSTEM_PROMPT_DATA_CONTEXT",
    "_MODEL_PRICING",
    "_DEFAULT_PRICING",
    # classification
    "classify_columns_semantic",
    "_wrap_exact_match",
    "_llm_classify_columns",
    "_safe_semantic_type",
    # schema
    "_SCHEMA_CACHE_PREFIX",
    "_SCHEMA_LOCK_PREFIX",
    "_LOCK_TTL_SECONDS",
    "_LOCK_POLL_INTERVAL_SECONDS",
    "_LOCK_POLL_TIMEOUT_SECONDS",
    "analyze_schema",
    "_poll_for_schema",
    "_compute_schema",
    "_extract_sheets_from_doc",
    "_parse_csv_schema",
    "_parse_excel_schema",
    "_parse_pdf_schema",
    "_parse_docx_schema",
    "_parse_image_schema",
    "_parse_prose_schema",
    "_extract_markdown_table_as_csv",
    "_enrich_sheets_with_llm",
    "_generate_schema_summary",
    # query
    "_DOC_COST_PREFIX",
    "_DOC_COST_TTL_SECONDS",
    "_QUERY_CACHE_PREFIX",
    "_QUERY_KEYS_PREFIX",
    "_QUERY_CACHE_TTL_SECONDS",
    "_TABULAR_SEMAPHORE_LIMIT",
    "_TABULAR_ROWS_PER_CHUNK",
    "_TABULAR_CHUNK_MAX_CHARS",
    "_PROSE_SEMAPHORE_LIMIT",
    "_PROSE_CHUNK_SIZE",
    "_MD_TABLE_ROW_RE",
    "query_document",
    "_query_document_impl",
    "_load_schema",
    "_build_query_plan",
    "_extract_tabular",
    "_parse_markdown_table",
    "_extract_tabular_llm",
    "_chunk_tabular_text",
    "_extract_tabular_chunk",
    "_merge_chunk_results",
    "_extract_prose",
    "_extract_from_chunk",
    "_filter_columns",
    "_get_query_cache_key",
    "_load_query_cache",
    "_store_query_cache",
    "invalidate_query_cache",
    "_check_budget",
    "_log_query_cost",
    "_estimate_cost",
    "_accumulate_usage",
]
