"""Document query execution for the document intelligence package.

Implementation lives in ``app.document_intelligence``.  Symbols are re-exported
here so consumers can import from either location.
"""
from __future__ import annotations

from app.document_intelligence import (
    _DOC_COST_PREFIX,
    _DOC_COST_TTL_SECONDS,
    _MD_TABLE_ROW_RE,
    _PROSE_CHUNK_SIZE,
    _PROSE_SEMAPHORE_LIMIT,
    _QUERY_CACHE_PREFIX,
    _QUERY_CACHE_TTL_SECONDS,
    _QUERY_KEYS_PREFIX,
    _TABULAR_CHUNK_MAX_CHARS,
    _TABULAR_ROWS_PER_CHUNK,
    _TABULAR_SEMAPHORE_LIMIT,
    _accumulate_usage,
    _build_query_plan,
    _check_budget,
    _chunk_tabular_text,
    _estimate_cost,
    _extract_from_chunk,
    _extract_prose,
    _extract_tabular,
    _extract_tabular_chunk,
    _extract_tabular_llm,
    _filter_columns,
    _get_query_cache_key,
    _load_query_cache,
    _load_schema,
    _log_query_cost,
    _merge_chunk_results,
    _parse_markdown_table,
    _query_document_impl,
    _store_query_cache,
    invalidate_query_cache,
    query_document,
)

__all__ = [
    "_DOC_COST_PREFIX",
    "_DOC_COST_TTL_SECONDS",
    "_QUERY_CACHE_PREFIX",
    "_QUERY_KEYS_PREFIX",
    "_QUERY_CACHE_TTL_SECONDS",
    "_TABULAR_SEMAPHORE_LIMIT",
    "_TABULAR_ROWS_PER_CHUNK",
    "_TABULAR_CHUNK_MAX_CHARS",
    "_PROSE_SEMAPHORE_LIMIT",
    "_PROSE_CHUNK_SIZE",
    "_MD_TABLE_ROW_RE",
    "query_document",
    "_query_document_impl",
    "_load_schema",
    "_build_query_plan",
    "_extract_tabular",
    "_parse_markdown_table",
    "_extract_tabular_llm",
    "_chunk_tabular_text",
    "_extract_tabular_chunk",
    "_merge_chunk_results",
    "_extract_prose",
    "_extract_from_chunk",
    "_filter_columns",
    "_get_query_cache_key",
    "_load_query_cache",
    "_store_query_cache",
    "invalidate_query_cache",
    "_check_budget",
    "_log_query_cost",
    "_estimate_cost",
    "_accumulate_usage",
]
