from __future__ import annotations

from typing import Any

import asyncpg

from ._pool import _acquire


def _monitor_row_to_dict(row: asyncpg.Record) -> dict[str, Any]:
    d = dict(row)
    if "id" in d and d["id"] is not None:
        d["id"] = str(d["id"])
    for ts in ("last_run_at", "next_run_at", "created_at"):
        if ts in d and d[ts] is not None:
            d[ts] = d[ts].isoformat()
    return d


async def db_create_monitor(owner_sid: str, label: str, query: str, frequency: str) -> dict[str, Any]:
    async with _acquire() as conn:
        row = await conn.fetchrow(
            """
            INSERT INTO playbook.monitors (owner_sid, label, query, frequency)
            VALUES ($1, $2, $3, $4)
            RETURNING *
            """,
            owner_sid, label, query, frequency,
        )
    return _monitor_row_to_dict(row)


async def db_list_monitors(owner_sid: str) -> list[dict[str, Any]]:
    async with _acquire() as conn:
        rows = await conn.fetch(
            "SELECT * FROM playbook.monitors WHERE owner_sid = $1 ORDER BY created_at DESC",
            owner_sid,
        )
    return [_monitor_row_to_dict(r) for r in rows]


async def db_delete_monitor(monitor_id: str, owner_sid: str) -> bool:
    async with _acquire() as conn:
        result = await conn.execute(
            "DELETE FROM playbook.monitors WHERE id = $1::uuid AND owner_sid = $2",
            monitor_id, owner_sid,
        )
    return result.endswith("1")


async def db_get_monitor(monitor_id: str, owner_sid: str) -> dict[str, Any] | None:
    async with _acquire() as conn:
        row = await conn.fetchrow(
            "SELECT * FROM playbook.monitors WHERE id = $1::uuid AND owner_sid = $2",
            monitor_id, owner_sid,
        )
    return _monitor_row_to_dict(row) if row else None


async def db_update_monitor(monitor_id: str, owner_sid: str, patch: dict[str, Any]) -> dict[str, Any] | None:
    allowed = {"label", "query", "frequency", "is_active"}
    sets = []
    vals: list[Any] = []
    idx = 3
    for k, v in patch.items():
        if k in allowed and v is not None:
            idx += 1
            sets.append(f"{k} = ${idx}")
            vals.append(v)
    if not sets:
        return await db_get_monitor(monitor_id, owner_sid)
    sql = f"UPDATE playbook.monitors SET {', '.join(sets)} WHERE id = $1::uuid AND owner_sid = $2 RETURNING *"
    async with _acquire() as conn:
        row = await conn.fetchrow(sql, monitor_id, owner_sid, *vals)
    return _monitor_row_to_dict(row) if row else None


async def db_list_monitor_runs(monitor_id: str, owner_sid: str) -> list[dict[str, Any]]:
    """Find sessions that were generated by a monitor (matching query + owner)."""
    async with _acquire() as conn:
        monitor = await conn.fetchrow(
            "SELECT query, owner_sid FROM playbook.monitors WHERE id = $1::uuid AND owner_sid = $2",
            monitor_id, owner_sid,
        )
        if not monitor:
            return []
        rows = await conn.fetch(
            """
            SELECT id, title, query, created_at
            FROM playbook.sessions
            WHERE owner_sid = $1 AND query = $2
            ORDER BY created_at DESC
            LIMIT 50
            """,
            monitor["owner_sid"], monitor["query"],
        )
    result = []
    for r in rows:
        d = dict(r)
        if "id" in d and d["id"] is not None:
            d["id"] = str(d["id"])
        if "created_at" in d and d["created_at"] is not None:
            d["created_at"] = d["created_at"].isoformat()
        result.append(d)
    return result


async def db_get_due_monitors() -> list[dict[str, Any]]:
    async with _acquire() as conn:
        rows = await conn.fetch(
            "SELECT * FROM playbook.monitors WHERE next_run_at <= NOW() AND is_active = TRUE ORDER BY next_run_at ASC"
        )
    return [_monitor_row_to_dict(r) for r in rows]


async def db_update_monitor_run(monitor_id: str, frequency: str) -> None:
    interval = "1 day" if frequency == "daily" else "7 days"
    async with _acquire() as conn:
        await conn.execute(
            f"UPDATE playbook.monitors SET last_run_at = NOW(), next_run_at = NOW() + INTERVAL '{interval}' "
            "WHERE id = $1::uuid",
            monitor_id,
        )
